### ISSUE TITLE
Footer text

### ISSUE THREAD

**Issue by ghost** [47deg/org#11]
We currently have a corporate copyright notice, we may want to change it to something else:

![copy](https://cloud.githubusercontent.com/assets/409039/20480828/8cf73e52-afe4-11e6-83ba-abb41139fa83.png)

**Comment by ghost** [comment]
@MaureenElsberry you can see it in https://47deg.github.io/org/

Should we change it to something along the lines of "Built with <3 with 47 degree's org"? Let us know!

**Comment by MaureenElsberry** [comment]
So sorry - I wasn't getting alerts for these somehow!!! I didn't know this existed 

I think it's sometimes good to have the corporate footers consistent among pages  - though we've dropped the Reactive portion - but I would be fine personally if you put something like "47 Degrees - crafted with love for the open-source community 

or something to that regard.

**Comment by ghost** [comment]
Will do, thanks!
