### ISSUE TITLE
Publish 47deg org site as an organization page.

### ISSUE THREAD

**Issue by raulraja** [47deg/org#23]
We need the 47deg reference implementation of 'org' for the 47deg organization published in a organization pages as described in https://help.github.com/articles/user-organization-and-project-pages/
so users can get to it directly when going to the organization page in Github (Also update description there to include link).
This will result with 47deg published at https://47deg.github.io

**Comment by jorgegalindocruces** [comment]
Hi @dialelo, what is the status of this? 

Thanks bro!

**Comment by ghost** [comment]
On it.

**Comment by ghost** [comment]
Its already published, looking forward to merge the remaining PRs in this repo so I can update the site: https://47deg.github.io/

**Comment by ghost** [comment]
I've updated the site with the latest changes https://47deg.github.io/ Closing this for now, I'm looking into automatically deploying org changes to the official site.
