### ISSUE TITLE
Links in the header

### ISSUE THREAD

**Issue by jorgegalindocruces** [47deg/org#39]
Hi!

We have to be linked our talks in the header, I think that make sense because it is a community site. 

This is the link -> https://fortyseven-site-pr-313.herokuapp.com/presentations/

BTW @MaureenElsberry, another link that do you think interesting to add?

**Comment by ghost** [comment]
Nice, I'm guessing its http://www.47deg.com/presentations/

I can add it under a "Talks" or "Presentations" link, let me know @MaureenElsberry.

**Comment by jorgegalindocruces** [comment]
yep, thanks to keep the eye @dialelo. We called it Talks in our website, so, i think that this is the way to do it!
