### ISSUE TITLE
Configuration improvements

### ISSUE THREAD

**Issue by ghost** [47deg/org#41]
- Spec for the configuration, check config validity before building site
- Make a sample config in `resources/config.example.edn` so users can start their site from it
- Encript 47deg site's config and add it to the repo
- Build the 47deg site decrypting the file in Travis CI

**Comment by purrgrammer** [comment]
No need to encrypt/decrypt config files since the config doesn't contain any secrets. It already has an spec for the config, checks config validity and the repo includes a sample configuration so I'm closing this one.
