### ISSUE TITLE
Project whitelist

### ISSUE THREAD

**Issue by ghost** [47deg/org#5]
We need to create the list with the repos we want to see in our open source page.

**Comment by ghost** [comment]
@raulraja this is a [first approach](https://github.com/47deg/org/blob/master/resources/config.edn#L7-L18), let me know if i should add or remove anything. You may also want to take a look at the relevant languages (have included Scala, Clojure, Swift & Java at the moment).

**Comment by MaureenElsberry** [comment]
Is there a reason Scala Exercises isn't included @dialelo? Just noticed it wasn't on there.

**Comment by raulraja** [comment]
It's in a different organization, we need the ability to also add any
arbitrary project on GitHub to the list. @dialelo do you have a rough idea
on the complexity of doing it so we can scope the work? . I'd like this to
be announced right after our new web.

**Comment by ghost** [comment]
Shouldn't be too difficult, I'll add another setting to include repos from other organizations. Should I add more projects or just Scala exercises? I can open a PR this afternoon with those changes.
