### ISSUE TITLE
Using for user (VS org) projects?

### ISSUE THREAD

**Issue by manosbatsis** [47deg/org#71]
Can org be used for a user (VS org)'s projects? I tried with using a user instead of an org handle, as well as a dummy (but existing) org in combination with `:extra-repos` but no dice.

**Comment by manosbatsis** [comment]
Don't speak clojure but, in case it helps a future search, i was able to pull the user repos by using the username as the org and changting `org-repos-url` in _org/client.cljc:47_  to `"https://api.github.com/users/" org "/repos"`

**Comment by purrgrammer** [comment]
Yep, you are right. Anybody who wants this to work for users just has to change the base URL. I'm closing this issue for now, since it's out of the scope of the project to work for users and is pretty straightforward to adapt it if you need to.
